package("endstone")
   add_urls("https://raw.githubusercontent.com/YoumiHa/endstone/main/endstone.tar")
   add_versions("latest","ed904fc38a54afb000ad1374000a0189e3c207650ad7ddfb40043a28d5eae8f5")
    on_install("windows", function (package)
        os.exec("start build.bat")
        os.cp("lib/include/bedrock", package:installdir("include"))
        os.cp("lib/include/endstone", package:installdir("include"))
        os.cp("lib/endstone_runtime.lib", package:installdir("lib"))
    end)
